[package]
name = "simple-project"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
redundant_pub_crate = "warn"
correctness = "warn"
performance = "warn"
style = "warn"
